### ISSUE TITLE
Update psr/log dependency so it can be used with projects using monolog 3 (php 8)

### ISSUE THREAD

**Issue by jez500** [voku/httpful#14]
#### What is this feature about (expected vs actual behaviour)?
This package has a `psr/log` dependency of `1.1.*` which makes it incompatible with any project that is using 
[monolog/monolog](https://packagist.org/packages/monolog/monolog) >= `3.*` (php 8). This results in dependency 
conflicts with newer projects, specifically [Laravel 10](https://laravel.com/docs/10.x/upgrade#monolog-3).

Example: [matomo-php-api](https://packagist.org/packages/visualappeal/matomo-php-api) requires this packages so 
it cannot be installed on anything using monolog >=3 (eg Laravel)

#### How can I reproduce it?
```
composer init
composer require monolog/monolog:3.*
composer require voku/httpful
```
results in 
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - voku/httpful[2.4.0, ..., 2.4.7] require psr/log 1.1.* -> found psr/log[1.1.0, ..., 1.1.4] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires voku/httpful ^2.4 -> satisfiable by voku/httpful[2.4.0, ..., 2.4.7].
```

#### Does it take minutes, hours or days to fix?
Potentially minutes if relaxing the dependency requirements to something like
```
  "psr/log": "1.1.*|2.*|3.*"
```
But that may break something deeper resulting in hours.

**Comment by theteknocat** [comment]
Plus 1 on this, as I currently have a Laravel project and am using a library that uses voku/httpful, thus running into this exact problem. But because it's a chain of dependencies, a workaround would be a pain in the butt.

**Comment by voku** [comment]
I updated the psr/* dependencies in >= 3.0.0
