### ISSUE TITLE
Request Body Not Preserved

### ISSUE THREAD

**Issue by XedinUnknown** [voku/httpful#7]
When configuring a request to use a specific body stream, the body content gets serialized. This should not happen.

```php
use Httpful\Request;
use Httpful\Factory;

$factory = new Factory;
$request = (new Request('GET'))->withBody($factory->createStream('abc'));

if ((string) $request->getBody() !== 'abc') {
	throw new Exception('Wrong body');
}
```

Here, the request body will actually be a serialized array with 1 element containing `'abc'`, whereas it should be just `'abc'`. The request should not change body content it is explicitly provided with a string. With this problem it is not possible to simply send JSON data to a REST API using the PSR-7 request alone, without its non-interface methods.

**Comment by voku** [comment]
Thanks for the bug report, fixed in version 2.4.0

**Comment by XedinUnknown** [comment]
That was quick! Thanks!

**Comment by XedinUnknown** [comment]
Looks like the package didn't update on Packagist. Do you have auto update triggers set up?

**Comment by XedinUnknown** [comment]
False alarm, I hadn't seen the "update now" link in super-small print...
